/**
 * @fileoverview gRPC-Web generated client stub for example
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: example.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as example_pb from './example_pb';


export class MyServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorgetData = new grpcWeb.MethodDescriptor(
    '/example.MyService/getData',
    grpcWeb.MethodType.UNARY,
    example_pb.DataRequest,
    example_pb.DataResponse,
    (request: example_pb.DataRequest) => {
      return request.serializeBinary();
    },
    example_pb.DataResponse.deserializeBinary
  );

  getData(
    request: example_pb.DataRequest,
    metadata: grpcWeb.Metadata | null): Promise<example_pb.DataResponse>;

  getData(
    request: example_pb.DataRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: example_pb.DataResponse) => void): grpcWeb.ClientReadableStream<example_pb.DataResponse>;

  getData(
    request: example_pb.DataRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: example_pb.DataResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/example.MyService/getData',
        request,
        metadata || {},
        this.methodDescriptorgetData,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/example.MyService/getData',
    request,
    metadata || {},
    this.methodDescriptorgetData);
  }

}

